Created Book entity, repository, services
vsych321/online-book-store pull request #1
Opened 2023-10-14 14:56 UTC by vsych321

2023-10-15 13:46 UTC, evgenkolner approved these changes
good decision

2023-10-16 12:32 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few moments;)

2023-10-16 12:32 UTC, liliia-ponomarenko commented on src/main/java/bookstore/entity/Book.java
> +@Data
Lombok is a great library but be [attentive when using it with Entity](https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/) JFYI

2023-10-16 12:32 UTC, liliia-ponomarenko commented on src/main/java/bookstore/repository/impl/BookRepositoryImpl.java
> +    @Autowired
As of Spring Framework 4.3, an @Autowired annotation on such a constructor is no longer necessary if the target bean defines only one constructor to begin with. See [note here ](https://docs.spring.io/spring-framework/reference/core/beans/annotation-config/autowired.html)Let’s check it ;)

2023-10-16 12:32 UTC, liliia-ponomarenko commented on src/main/java/bookstore/repository/impl/BookRepositoryImpl.java
> +                    "select b from Book b", Book.class).getResultList();
```suggestion
                    "from Book", Book.class).getResultList();
```

2023-10-19 14:40 UTC, Elena-Bruyako approved these changes

2023-10-19 14:40 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/impl/BookRepositoryImpl.java
> +                    "from Book b", Book.class).getResultList();
```suggestion
                    "from Book", Book.class).getResultList();
```

2023-11-06 12:46 UTC, merged