made new branch with all the changes from main
vsych321/online-book-store pull request #11
Opened 2023-11-08 11:28 UTC by vsych321

2023-11-09 08:11 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2023-11-09 08:11 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
why do you need this dependency?

2023-11-09 08:11 UTC, liliia-ponomarenko commented on pom.xml
> +</project>
```suggestion
</project>

```

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/config/SecurityConfig.java
> +
```suggestion
```

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/controller/AuthenticationController.java
> +@Validated
```suggestion
```
you don’t  use this annotation

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.OK)
return CREATED

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.OK)
OK it’s  default status

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/dto/user/UserLoginRequestDto.java
> +        @Size(min = 8)
should you add max size?

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/dto/user/UserLoginRequestDto.java
> +        @Size(min = 8)
the same

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/dto/user/UserResponseDto.java
> +
```suggestion
```

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/dto/user/UserResponseDto.java
> +        Long id,
```suggestion
        Long id,
        
```
I'm not a fan of empty lines, but if you like it, stick to the same style in all your classes

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/entity/User.java
> +    @Column(name = "is_deleted")
```suggestion
    @Column(name = "is_deleted", nullable = false)
```

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/security/CustomUserDetailsService.java
> +                () -> new RuntimeException("Can't find user my email"));
```suggestion
                () -> new UsernameNotFoundException("Can't find user my email"));
```
and remove it from the signature

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
better make constant and you can use length instead magic number 7

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/service/impl/UserServiceImpl.java
> +        return userMapper.toUserResponse(savedUser);
can be an inline variable

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/validation/FiledMatcherValidator.java
> +        return requestDto.password().equals(requestDto.repeatPassword());
how about not null check?

2023-11-09 08:11 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                    nullable: false
one empty line (check other files)

2023-11-10 13:46 UTC, vsych321 commented on src/main/java/bookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.OK)
That's why I use it

2023-11-10 14:13 UTC, liliia-ponomarenko approved these changes
Great! 😌

2023-11-10 14:13 UTC, liliia-ponomarenko commented on src/main/java/bookstore/validation/FiledMatcherValidator.java
> +        return false;
can you use the ternary operator?

2023-11-13 13:12 UTC, merged