Book order setup
vsych321/online-book-store pull request #15
Opened 2023-12-02 15:58 UTC by vsych321

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko requested changes
Nice job, lets make it better

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/controller/OrderController.java
> +    @PostMapping
```suggestion
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
```

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/controller/OrderController.java
> +            Authentication authentication) {
add pageable

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/controller/OrderController.java
> +        return orderService.getOrderItemById(orderId,authentication,itemId);
```suggestion
        return orderService.getOrderItemById(orderId, authentication, itemId);
```

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/dto/order/itemdto/OrderItemResponseDto.java
> +) {
maybe you`ve forgotten about price?

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/dto/orderdto/OrderResponseDto.java
> +) {
also forgot about shipping address?

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/entity/OrderItem.java
> +public class OrderItem {
there are no overriden equals, hashcode; toString(not necessary)

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/entity/Order.java
> +public class Order {
there are no overriden equals, hashcode; toString(not necessary)

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/service/impl/OrderServiceImpl.java
> +
blank line

2023-12-02 18:36 UTC, Oleksandr-Tymoshenko commented on src/main/java/bookstore/service/impl/OrderServiceImpl.java
> +        orderRepository.findByIdAndUserId(orderId, user.getId());
what is it for? You don`t use the result of findOrderByID

2023-12-04 11:22 UTC, vsych321 commented on src/main/java/bookstore/dto/order/itemdto/OrderItemResponseDto.java
> +) {
price is mentioned in order response, not item)

2023-12-04 11:23 UTC, vsych321 commented on src/main/java/bookstore/dto/orderdto/OrderResponseDto.java
> +) {
the same as with price, mb it's personal info

2023-12-06 07:35 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-12-06 07:35 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/order/OrderRepository.java
> +public interface OrderRepository extends JpaRepository<Order, Long> {
```suggestion
@Repository
public interface OrderRepository extends JpaRepository<Order, Long> {
```

2023-12-06 07:35 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/order/item/OrderItemRepository.java
> +
```suggestion
```

2023-12-06 07:35 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/orderdto/OrderWithoutItemsDto.java
> +public record OrderWithoutItemsDto(
Why do you need this dto?

2023-12-06 07:35 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/OrderService.java
> +
```suggestion
```

2023-12-06 07:35 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/impl/OrderServiceImpl.java
> +        User user = (User) userDetailsService.loadUserByUsername(authentication.getName());
Let's create private method for getting user to avoid duplication

2023-12-06 07:35 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/impl/OrderServiceImpl.java
> +
```suggestion
```

2023-12-06 07:35 UTC, Elena-Bruyako commented on src/main/java/bookstore/service/impl/OrderServiceImpl.java
> +    private Set<OrderItem> setItems(Order order, Set<CartItem> cartItems) {
private methods should be replaces after all public methods

2023-12-06 10:42 UTC, vsych321 commented on src/main/java/bookstore/dto/orderdto/OrderWithoutItemsDto.java
> +public record OrderWithoutItemsDto(
cz I have an empty list of orderItems

2023-12-06 11:15 UTC, liliia-ponomarenko requested changes
Let’s fix your createOrder method ;)

2023-12-07 10:05 UTC, liliia-ponomarenko approved these changes
Great 😊

2023-12-10 13:20 UTC, merged