Book security setup
vsych321/online-book-store pull request #6
Opened 2023-11-05 17:58 UTC by vsych321

2023-11-06 06:11 UTC, validatorr approved these changes
Great job, keep going!

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**")
you should also add access to swagger

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/controller/AuthenticationController.java
> +            throws RegistrationException {
`public UserResponseDto register(@RequestBody @Valid UserRegistrationRequestDto request) {`

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/controller/AuthenticationController.java
> +
it would be also great if you add @Tag and description to all methods

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.ACCEPTED)
It's actually OK response (and in all other methods)
https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.3

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/dto/CreateBookRequestDto.java
> +         String coverImage
do you allow books not to have photo or description?

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/dto/user/UserRegistrationRequestDto.java
> +public record UserRegistrationRequestDto(
add also constraints for max value, in order to provide checked data to our DB

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/entity/Role.java
> +@Where(clause = "is_deleted=false")
do you really need soft delete in roles?

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/exception/EntityNotFoundException.java
> +    }
do you use both of this constructors?

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
HttpHeaders.AUTHORIZATION you can use this also

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
extend it from RuntimeException and you won't have to specify in each place of your code `throws RegistrationException`

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
better use existsByEmail in your UserRepository(it will return boolean)

2023-11-06 06:11 UTC, validatorr commented on src/main/java/bookstore/validation/FiledMatcherValidator.java
> +
you don't have initialize method, or is it working without it?

2023-11-06 06:11 UTC, validatorr commented on src/main/resources/application.properties
> +spring.profiles.active=test
that's interesting, I'm wondering why did you set it on test?

2023-11-06 06:11 UTC, validatorr commented on src/test/resources/application-test.properties
> +server.servlet.context-path=/api
did you check if it's going to work the same if you won't put it in test properties?

2023-11-06 10:43 UTC, liliia-ponomarenko requested changes
I see changes from the previous  HW. Let’s  fix it! (you can find the issue in the question channel)

2023-11-07 08:24 UTC, NazarSmith228 requested changes
1. Your PR contains much more changes than just Security task :)
2. Your PR has merge conflicts

Pls resolve that before submitting it for review

2023-11-30 11:21 UTC, closed without merging